version: '3.8'

services:
  app:
    image: atxiaoheicat/copilpt:latest
    build: .
    ports:
      - "7860:7860"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}